### ISSUE TITLE
Error while lifting.

### ISSUE THREAD

**Issue by anzosasuke** [microsoft/llvm-mctoll#193]
I encountered error when i am trying to lift the x64 binary. How do i fix this?
i have attached the binary file as well.

``` 
a967a038:/data/llvm-project/build/bin$ ./llvm-mctoll -d sclang 
llvm-mctoll: /data/llvm-project/llvm/tools/llvm-mctoll/X86/X86MachineInstructionRaiserUtils.cpp:1531: llvm::Function* llvm::mctoll::X86MachineInstructionRaiser::getTargetFunctionAtPLTOffset(const llvm::MachineInstr&, uint64_t): Assertion `(GotPltReloc->getType() == ELF::R_X86_64_JUMP_SLOT) && "Unexpected relocation type for PLT jmp instruction"' failed.

*** Please submit an issue at https://github.com/microsoft/llvm-mctoll
*** along with a back trace and a reproducer, if possible.
Stack dump:
0.	Program arguments: ./llvm-mctoll -d sclang
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  llvm-mctoll 0x00005599d20906a0
1  llvm-mctoll 0x00005599d2090a76
2  llvm-mctoll 0x00005599d208e28d
3  llvm-mctoll 0x00005599d208ff9e
4  libc.so.6   0x00007f1129414520
5  libc.so.6   0x00007f1129468a7c pthread_kill + 300
6  libc.so.6   0x00007f1129414476 raise + 22
7  libc.so.6   0x00007f11293fa7f3 abort + 211
8  libc.so.6   0x00007f11293fa71b
9  libc.so.6   0x00007f112940be96
10 llvm-mctoll 0x00005599d2971ef6
11 llvm-mctoll 0x00005599d2992246
12 llvm-mctoll 0x00005599d2990049
13 llvm-mctoll 0x00005599d2943b1e
14 llvm-mctoll 0x00005599d1023f26
15 llvm-mctoll 0x00005599d1024a0e
16 llvm-mctoll 0x00005599d1025094
17 llvm-mctoll 0x00005599d10353c4
18 llvm-mctoll 0x00005599d1026336
19 libc.so.6   0x00007f11293fbd90
20 libc.so.6   0x00007f11293fbe40 __libc_start_main + 128
21 llvm-mctoll 0x00005599d101ed55
Aborted (core dumped)

```
[sclang.zip](https://github.com/microsoft/llvm-mctoll/files/12653761/sclang.zip)

**Comment by bharadwajy** [comment]
Thanks for your interest in the project.

I have pushed a change to relax the assertion to handle the relocation type `R_X86_64_GLOB_DAT`.

Let me know if that helps.

**Comment by anzosasuke** [comment]
Thanks. But i am still getting the same error after that.

``llvm-mctoll: /data/llvm-project/llvm/tools/llvm-mctoll/X86/X86MachineInstructionRaiserUtils.cpp:1531: llvm::Function* llvm::mctoll::X86MachineInstructionRaiser::getTargetFunctionAtPLTOffset(const llvm::MachineInstr&, uint64_t): Assertion `(GotPltReloc->getType() == ELF::R_X86_64_JUMP_SLOT) && "Unexpected relocation type for PLT jmp instruction"' failed.

*** Please submit an issue at https://github.com/microsoft/llvm-mctoll
*** along with a back trace and a reproducer, if possible.
Stack dump:
0.	Program arguments: ./llvm-mctoll -d sclang
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  llvm-mctoll 0x0000558dac9fca56
1  llvm-mctoll 0x0000558dac9fa43e
2  libc.so.6   0x00007f59c9caf520
3  libc.so.6   0x00007f59c9d03a7c pthread_kill + 300
4  libc.so.6   0x00007f59c9caf476 raise + 22
5  libc.so.6   0x00007f59c9c957f3 abort + 211
6  libc.so.6   0x00007f59c9c9571b
7  libc.so.6   0x00007f59c9ca6e96
8  llvm-mctoll 0x0000558dad04c36b
9  llvm-mctoll 0x0000558dad063c6f
10 llvm-mctoll 0x0000558dad02c3cd
11 llvm-mctoll 0x0000558dac19f51d
12 llvm-mctoll 0x0000558dac13f942
13 libc.so.6   0x00007f59c9c96d90
14 libc.so.6   0x00007f59c9c96e40 __libc_start_main + 128
15 llvm-mctoll 0x0000558dac18d1c5
Aborted (core dumped)
```

I have attached the file at the top if you want to recreate.

**Comment by bharadwajy** [comment]
> Thanks. But i am still getting the same error after that.
> 
> ``llvm-mctoll: /data/llvm-project/llvm/tools/llvm-mctoll/X86/X86MachineInstructionRaiserUtils.cpp:1531: llvm::Function* llvm::mctoll::X86MachineInstructionRaiser::getTargetFunctionAtPLTOffset(const llvm::MachineInstr&, uint64_t): Assertion `(GotPltReloc->getType() == ELF::R_X86_64_JUMP_SLOT) && "Unexpected relocation type for PLT jmp instruction"' failed.
> 

It appears that you need to pull the `llvm-mctoll` repo as that line has been part of the change I pushed - see [here](https://github.com/microsoft/llvm-mctoll/blob/7f71a898fbffb0229d45b8115c62784f5cd9558e/X86/X86MachineInstructionRaiserUtils.cpp#L1531). Rebuild `llvm-mctoll` once you update your `llvm-mctoll` repo.

I have verified that the change works using the `sclang` binary you provided earlier before I pushed.

**Comment by anzosasuke** [comment]
Thanks so much. It worked. I was just pulling llvm project instead of llvm-mctoll. But i am getting this:
``` Unknown prototype for function : strcmp
Use -I </full/path/to/file>, where /full/path/to/file declares its prototype```

Do we need the include file to get the llvm IR? If we actually need to put it, does that mean some portion of source is needed to lift binary to IR? and when using the command "llvm-mctoll -d <binary>" yield the result in the interface itself?

**Comment by bharadwajy** [comment]
> Thanks so much. It worked. I was just pulling llvm project instead of llvm-mctoll. But i am getting this:
> 
> ```
> Unknown prototype for function : strcmp
> Use -I </full/path/to/file>, where /full/path/to/file declares its prototype
> ```
> 
> Do we need the include file to get the llvm IR? If we actually need to put it, does that mean some portion of source is needed to lift binary to IR? and when using the command "llvm-mctoll -d " yield the result in the interface itself?

You do not need any portion of the source file. You will need to provide the _prototypes_ of externally linked functions (such as `strcmp`) for `llvm-mctoll` to help the process of raising as described [here](https://github.com/microsoft/llvm-mctoll/blob/master/doc/Usage.md#specifying-prototypes-of-functions-externally-referenced-in-the-binary-being-raised). `llvm-mctoll` cannot figure out the prototypes of externally linked functions just using the binary.

For example, here is a **portion** of the file I created with external (i.e., `glibc`) function prototypes to ensure that the tool makes progress beyond the assertion fix I made while raising your binary.

```
$ cat myinclude.h
#include <stddef.h>

int strcmp(const char *s1, const char *s2);
int strncmp(const char *s1, const char *s2, size_t n);
char *strcpy(char *dest, const char *src);
size_t strlen(const char *s);
char *strndup(const char *s, size_t n);
char *strdup(const char *s);

$ llvm-mctoll -d -I /full/path/to/myinclude.h sclang
```

Please note that I have not added all the necessary prototypes. Please add any additional prototypes to check if your `sclang` binary can be raised by `llvm-mctoll`.

**Comment by anzosasuke** [comment]
Got it. Thanks so much.
